show databases;
use cac;
show tables;
desc tb_atendimento;
select * from tb_atendimento;

alter table tb_salas
drop column data;

alter table tb_atendimento
rename to tb_atendimentos;

drop table tb_atendimento;
show tables;

insert into tb_atendimentos(cpf, numero_atendimento, sufixo_atendimento, data_atendimento, emissao_atendimento)
values ("11122233344", "02", 'PDG', '2022-04-17', '2022-04-17 19:59:53');

-- MySQL Script generated by MySQL Workbench
-- dom 17 abr 2022 16:44:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cac
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cac
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cac` DEFAULT CHARACTER SET utf8 ;
USE `cac` ;

-- -----------------------------------------------------
-- Table `cac`.`tb_atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cac`.`tb_atendimento` (
  `id_atendimento` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(12) NOT NULL,
  `numero_atendimento` VARCHAR(4) NOT NULL,
  `sufixo_atendimento` ENUM('PDG', 'FCR', 'DRT', 'OTS') NOT NULL,
  `observacoes` VARCHAR(280) NULL,
  `data_atendimento` DATE NOT NULL,
  `emissao_atendimento` TIMESTAMP NOT NULL,
  `inicio_atendimento` VARCHAR(45) NULL,
  `estado_fim_atendimento` ENUM('nao_concluido', 'concluido') NULL,
  `fim_atendimento` TIMESTAMP NULL,
  INDEX `index1` (`id_atendimento` ASC) VISIBLE,
  PRIMARY KEY (`id_atendimento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cac`.`tb_historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cac`.`tb_historico` (
  `id_atendimento` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(12) NOT NULL,
  `numero_atendimento` VARCHAR(4) NOT NULL,
  `sufixo_atendimento` ENUM('PDG', 'FCR', 'DRT', 'OTS') NOT NULL,
  `observacoes` VARCHAR(280) NULL,
  `data_atendimento` DATE NOT NULL,
  `emissao_atendimento` TIMESTAMP NOT NULL,
  `inicio_atendimento` VARCHAR(45) NULL,
  `estado_fim_atendimento` ENUM('nao_concluido', 'concluido') NULL,
  `fim_atendimento` TIMESTAMP NULL,
  INDEX `index1` (`id_atendimento` ASC) VISIBLE,
  PRIMARY KEY (`id_atendimento`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
