name: CI

on:
  push:
    branches: [ "servidor" ]

jobs:
  laravel-tests:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        php-version: '8.0'

    - uses: actions/cache@v2
      with:
        path: ~/.composer/cache/files
        key: dependencies-composer-${{ hashFiles('composer.json') }}
    
    - name: Clean configs
      run: php artisan config:clear 

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    
    - name: Install Dependencies
      run: 
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Autoload
      run: composer dumpautoload
    
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Connection Sqlite
      env:
        APP_URL: http://localhost:8000
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        DB_PORT: 8889
      run: php artisan migrate --env=production --seed

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php artisan test
